name: shrine
description: Learn the basics of using Material Components by building a simple app with core components.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.5
  shrine_images: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
  uses-material-design: true
  assets:
    - assets/watch.png
    # TODO: Add slanted menu asset (104)
    - assets/slanted_menu.png
    - assets/watches/png-transparent-silver-apple-watch-with-white-sports-band-apple-watch-series-3-apple-watch-series-2-apple-watch-series-1-apple-watch-accessory-sport-apple-watch-thumbnail.png
    - assets/watches/png-transparent-calvin-klein-collection-watch-bracelet-fashion-calvin-klein-women-watch-bracelet-holidays-women-accessories-bracelet-thumbnail.png
    - assets/watches/png-transparent-apple-watch-series-3-apple-watch-series-2-smartwatch-watch-electronics-watch-accessory-accessories-thumbnail.png
    - assets/watches/png-transparent-nike-apple-watch-series-3-apple-watch-series-2-nike-watch-accessory-apple-watch-smartwatch-thumbnail.png
    - assets/watches/png-transparent-apple-watch-series-3-apple-watch-series-2-apple-watch-series-1-smart-house-electronics-sport-apple-watch-thumbnail.png
    - assets/watches/png-transparent-michael-kors-watch-fashion-handbag-woman-luxury-watches-watch-accessory-accessories-diamond-thumbnail.png
    - assets/watches/png-transparent-watch-strap-chronograph-armani-watch-brown-watch-accessory-bracelet-thumbnail.png
    - assets/watches/png-transparent-tissot-automatic-watch-luxury-goods-jewellery-tissot-mechanical-watches-electronics-watch-accessory-mens-thumbnail.png
    - assets/watches/png-transparent-apple-watch-series-2-apple-watch-series-3-pebble-apple-white-smart-watch-white-watch-accessory-computer-thumbnail.png
    - assets/watches/png-transparent-watch-casio-edifice-g-shock-water-resistant-mark-casio-men-s-waterproof-watches-electronics-watch-accessory-leather-thumbnail.png
    - assets/watches/png-transparent-apple-watch-series-3-apple-watch-series-2-apple-watch-series-1-green-cong-electronics-watch-accessory-apple-watch-thumbnail.png
    - assets/watches/png-transparent-apple-watch-smartwatch-wearable-technology-apple-products-electronics-gadget-company-thumbnail.png
    - assets/watches/png-transparent-casio-f-91w-watch-casio-la670wega-amazon-com-watch-watch-accessory-accessories-steel-thumbnail.png
    - assets/watches/png-transparent-rolex-analog-watch-at-10-10-rolex-submariner-counterfeit-watch-rolex-gmt-master-ii-gold-rolex-watch-watches-gold-coin-watch-accessory-diamond-thumbnail.png
    - assets/watches/png-transparent-apple-watch-series-2-apple-watch-series-1-smartwatch-stainless-steel-black-smart-watch-black-hair-black-white-accessories-thumbnail.png
    - assets/watches/png-transparent-montblanc-automatic-watch-watch-strap-montblanc-watch-hand-silver-rim-m-exemplar-watch-accessory-hand-leather-thumbnail.png
    - assets/watches/png-transparent-round-black-rolex-analog-watch-with-bracelet-rolex-submariner-rolex-daytona-rolex-datejust-rolex-gmt-master-ii-black-male-watch-rolex-watch-black-hair-watch-accessory-black-white-thumbnail.png
    - assets/watches/png-transparent-automatic-watch-rolex-watch-strap-gold-watches-rolex-watches-female-form-watch-accessory-gold-coin-time-thumbnail.png
    - assets/watches/png-transparent-analog-watch-international-watch-company-calatrava-chronograph-cheetah-men-s-watches-animals-bracelet-watch-accessory-thumbnail.png
    - assets/watches/png-transparent-watch-quartz-clock-gold-watch-watch-accessory-accessories-diamond-thumbnail.png
    - assets/watches/png-transparent-pocket-watch-clock-men-s-watch-watch-accessory-poster-accessories-thumbnail.png
    - assets/watches/png-transparent-apple-watch-series-3-apple-watch-series-2-macbook-pro-apple-watch-series-3-thumbnail.png
    - assets/watches/png-transparent-bbcode-smart-watch-miscellaneous-electronics-gadget-thumbnail.png
    - assets/watches/png-transparent-skeleton-watch-automatic-watch-international-watch-company-refined-watches-watch-accessory-accessories-diamond-thumbnail.png
    - assets/watches/png-transparent-vacheron-constantin-gold-watch-movement-strap-vacheron-constantin-watches-black-watches-mechanical-male-watch-black-hair-watch-accessory-black-white-thumbnail.png
    - assets/watches/png-transparent-watch-clock-fashion-accessory-designer-women-s-watch-holidays-women-accessories-indian-nude-women-thumbnail.png
    - assets/watches/png-transparent-amazon-com-fossil-group-chronograph-watch-jewellery-omega-watch-watch-accessory-metal-watch-thumbnail.png
    - assets/watches/png-transparent-watch-chronograph-tissot-jewellery-strap-citizen-men-s-watch-watch-accessory-accessories-apple-watch-thumbnail.png
    - assets/watches/png-transparent-watch-strap-titan-company-metal-gold-ladies-watch-thumbnail.png
    - assets/watches/png-transparent-watch-strap-daniel-wellington-watch-watch-accessory-accessories-apple-watch-thumbnail.png
    - assets/watches/png-transparent-omega-speedmaster-tag-heuer-watch-chronograph-rolex-tag-heuer-watch-silver-wristwatch-male-watch-sale-tag-watch-accessory-mens-thumbnail.png
    - assets/watches/png-transparent-watch-strap-silver-women-watch-thumbnail.png
    - assets/watches/png-transparent-tudor-watches-rolex-oyster-wrist-watch-watch-accessory-bracelet-accessories-thumbnail.png
    - assets/watches/png-transparent-watch-clock-watch-accessory-retail-product-thumbnail.png
    - assets/watches/png-transparent-watch-icon-wristwatch-brown-watch-accessory-candle-thumbnail.png